version: "3.9"

services:
  dateguess-ui:
    build:
      context: ..
      dockerfile: docker/dateguess-ui/Dockerfile
      target: dev
    command: sh -c "npm rebuild node-sass && npm start"
    networks:
      - dateguess
    volumes:
      - ..:/dateguess-ui
    ports:
      - 3000:3000
    env_file: ../.env

networks:
  dateguess:
    name: dateguess
